language: python
install: pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: WLRzSpCBMC82wKfhJ2NDO0gyw7tOXv54Ngg4GaEVZ3ZQEEWqf10nwEnsppvdhteTvho5jRNICsar1jRyCgni2YVCrHK5ITRIdypP0BmV38IFsm2VXU2jJX3uuNHQgItmN3U9UWKpjzIQakdkhigRNze8LL6m0EfGSEO5GV0/OIzmBTWhEXCtBM3Q/eObxZGDq2yKZoUHk/YIzt/bYi3uXZnuEZic6bH4yu4CZVtFx5SGKWNxqq+pnwDzoxmqavp/R/xN3bZ3rigVC9LWe2JzuMbkJmk7ItZipBnDHK50r+b9o8GVhjNK95PwtT7EU5vVm24tFtyJZHRCp9ZDNotjiAOp6GvFVP7HygAiOVe9GJIFmuM4ZGdR23a3vl+Wa1s8S+0Mhd6gDBhql+Uk3TCwrtM9v9ivXCSRwwwJMI7I5N3dm/W6LCBYi/VNTn0stJR45O6SQ43v3IgC1gjnlYbOyhJv7SHdKYuMnFpIHv1e6DDP5Vp9ZSePjBoDQmTjuoFGHxApXhO1C9dcscB4G5M2COL/PKIEps8YwwoJEvhc1p0im32bdiBSPjRPCdfGG3TeODg3ZoXFZ6RJYWo3976e9F0H+mLDODX9rcc+Y+cOK9lLXbt5p1rrEZf9o0sppZCjxx8kXDdluHyKPHSg+Gvu37guT6rdlii8pc2PxfjyGwA=
app: icraig-team-m
script: python3 tests.py
